homepage
WildCodeSchool/2023-09-wns-vert-groupe1 pull request #45
Opened 2024-05-15 13:58 UTC by AndressaaRibeiro

2024-05-15 14:05 UTC, thuyannhu approved these changes

2024-05-16 08:59 UTC, YuliaKey requested changes

2024-05-16 08:59 UTC, YuliaKey commented on frontend/src/pages/index.tsx
> +						textAlign: "left",
Normalement tu n'as pas besoin de textAlign ici si tu a alignItems: "flex-start" dans le parent?

2024-05-16 09:28 UTC, AndressaaRibeiro commented on frontend/src/pages/index.tsx
> +					variant="h1"
a été corrigée

2024-05-16 09:28 UTC, AndressaaRibeiro commented on frontend/src/pages/index.tsx
> +						textAlign: "left",
A été corrigée

2024-05-16 09:28 UTC, AndressaaRibeiro commented on frontend/src/components/Layout.tsx
> +								background: mainTheme.palette.primary.dark,
A été corrigée

2024-05-16 09:37 UTC, AndressaaRibeiro commented
![Uploading Capture d’écran 2024-05-16 à 11.32.40.png…]()

2024-05-16 12:05 UTC, ludivinemartel approved these changes

2024-05-16 12:21 UTC, YuliaKey approved these changes

2024-05-16 12:22 UTC, merged