CRUD ADMIN USERS
WildCodeSchool/2023-09-wns-vert-groupe1 pull request #49
Opened 2024-06-14 08:41 UTC by ludivinemartel

https://github.com/WildCodeSchool/2023-09-wns-vert-groupe1/assets/126491075/9a1cff26-d273-44a9-98a7-558c0d5b479e

2024-06-14 10:00 UTC, sonm0002 commented on frontend/src/pages/admin/users.tsx
> +				<h1>Liste des utilisateurs</h1>
remplacer h1 par le composant typography de mui avec variant h1

2024-07-16 14:38 UTC, thuyannhu approved these changes
@ludivinemartel, je pense qu'il faudrait dans un second temps restreindre la vue en fonction des rôles et restreindre les actions d'édition en fonction des rôles. Par exemple, un City Admin ne peut voir que les users de sa ville et leur donner le rôle de Super User. Un Admin peut voir tous les users et donner les rôles de City Admin ou Super User.  Les autres ne peuvent pas voir la page.

2024-07-18 07:45 UTC, YuliaKey requested changes

2024-07-18 07:45 UTC, YuliaKey commented on backend/src/resolvers/User.ts
> +	async deleteUser(@Arg("userId") userId: string) {
pourquoi userId est une string?

2024-07-18 07:45 UTC, YuliaKey commented on frontend/src/context/RefetchContext.tsx
> +const RefetchContext = createContext<RefetchContextType | undefined>(undefined);
à quoi sert ce composant?

2024-07-18 07:45 UTC, YuliaKey commented on frontend/src/graphql/mutations/mutations.ts
> +	}
Pourquoi string?

2024-07-18 07:45 UTC, YuliaKey commented on frontend/src/pages/admin/categories/categories.tsx
> +const PageCategorie = () => {
On sait que c'est une page car le composant est dans le dossier pages, j'aurais renommé

2024-07-18 07:45 UTC, YuliaKey commented on frontend/src/pages/admin/pois/pois.tsx
> +const PagePois = () => {
nomage aussi

2024-07-18 07:57 UTC, closed without merging